import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AuthProvider from '@/supabase/Provider';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { ThemeProvider } from './components/shared/theme-provider';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Notion',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const supabase = createServerComponentClient(
        { cookies },
        {
            supabaseUrl: process.env
                .NEXT_PUBLIC_SUPABASE_URL as unknown as string,
            supabaseKey: process.env
                .NEXT_PUBLIC_SUPABASE_AVON_KEY as unknown as string,
        },
    );

    const {
        data: { session },
    } = await supabase.auth.getSession();

    return (
        <html lang='en'>
            <body className={cn(inter.className, 'h-full')}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <AuthProvider
                        accessToken={session?.access_token as unknown as string}
                    >
                        {children}
                    </AuthProvider>
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
